// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqyunulsvbilgucsmxlc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxeXVudWxzdmJpbGd1Y3NteGxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0NjMyMTcsImV4cCI6MjA3NjAzOTIxN30.GRDIlvZr8v9_4sSdmy8hE-bVJw1xAXCOeVoGPtOEZ7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});